export const nationalParks = [
  {
    id: 1,
    name: "Yellowstone",
    type: "National Park",
    state: "Wyoming, Montana, Idaho",
    description:
      "America's first national park, known for its wildlife and geothermal features, especially Old Faithful geyser.",
    established: 1872,
    visitors: 4860242,
    latitude: 44.428,
    longitude: -110.5885,
    website: "https://www.nps.gov/yell/index.htm",
    image: "/old-faithful-eruption.png",
  },
  {
    id: 2,
    name: "Grand Canyon",
    type: "National Park",
    state: "Arizona",
    description:
      "A steep-sided canyon carved by the Colorado River, known for its visually overwhelming size and intricate landscape.",
    established: 1919,
    visitors: 4732101,
    latitude: 36.0544,
    longitude: -112.2401,
    website: "https://www.nps.gov/grca/index.htm",
    image: "/grand-canyon-panorama.png",
  },
  {
    id: 3,
    name: "Yosemite",
    type: "National Park",
    state: "California",
    description:
      "Known for its waterfalls, giant sequoias, and spectacular granite cliffs like El Capitan and Half Dome.",
    established: 1890,
    visitors: 3287595,
    latitude: 37.8651,
    longitude: -119.5383,
    website: "https://www.nps.gov/yose/index.htm",
    image: "/half-dome-granite.png",
  },
  {
    id: 4,
    name: "Zion",
    type: "National Park",
    state: "Utah",
    description: "Known for its steep red cliffs, emerald pools, and the narrow slot canyon of the Virgin River.",
    established: 1919,
    visitors: 4692417,
    latitude: 37.2982,
    longitude: -113.0263,
    website: "https://www.nps.gov/zion/index.htm",
    image: "/zion-canyon-vista.png",
  },
  {
    id: 5,
    name: "Great Smoky Mountains",
    type: "National Park",
    state: "Tennessee, North Carolina",
    description:
      "America's most visited national park, known for its ancient mountains, diverse plant and animal life, and remnants of Southern Appalachian culture.",
    established: 1934,
    visitors: 12547743,
    latitude: 35.6118,
    longitude: -83.4895,
    website: "https://www.nps.gov/grsm/index.htm",
    image: "/smoky-mountain-fog.png",
  },
  {
    id: 6,
    name: "Acadia",
    type: "National Park",
    state: "Maine",
    description:
      "The oldest national park east of the Mississippi River, featuring the highest rocky headlands along the Atlantic coastline.",
    established: 1919,
    visitors: 3537575,
    latitude: 44.3386,
    longitude: -68.2733,
    website: "https://www.nps.gov/acad/index.htm",
    image: "/acadia-granite-shoreline.png",
  },
  {
    id: 7,
    name: "Olympic",
    type: "National Park",
    state: "Washington",
    description:
      "Features diverse ecosystems from glacier-capped mountains to old-growth temperate rainforests to over 70 miles of wild coastline.",
    established: 1938,
    visitors: 2718925,
    latitude: 47.8021,
    longitude: -123.6044,
    website: "https://www.nps.gov/olym/index.htm",
    image: "/Hoh Rainforest Canopy.png",
  },
  {
    id: 8,
    name: "Rocky Mountain",
    type: "National Park",
    state: "Colorado",
    description: "Known for its views of the Rocky Mountains, alpine lakes, and diverse mountain environments.",
    established: 1915,
    visitors: 4434848,
    latitude: 40.3428,
    longitude: -105.6836,
    website: "https://www.nps.gov/romo/index.htm",
    image: "/alpine-lake-reflection.png",
  },
  {
    id: 9,
    name: "Shenandoah",
    type: "National Park",
    state: "Virginia",
    description:
      "Located along the Blue Ridge Mountains, featuring cascading waterfalls, spectacular vistas, and quiet wooded hollows.",
    established: 1935,
    visitors: 1425507,
    latitude: 38.4755,
    longitude: -78.4535,
    website: "https://www.nps.gov/shen/index.htm",
    image: "/autumnal-shenandoah-vista.png",
  },
  {
    id: 10,
    name: "Everglades",
    type: "National Park",
    state: "Florida",
    description:
      "The largest subtropical wilderness in the United States, protecting an unparalleled landscape of sawgrass marshes, mangrove forests, and hardwood hammocks.",
    established: 1947,
    visitors: 1118300,
    latitude: 25.3866,
    longitude: -80.5831,
    website: "https://www.nps.gov/ever/index.htm",
    image: "/everglades-airboat-through-sawgrass.png",
  },
  {
    id: 11,
    name: "Arches",
    type: "National Park",
    state: "Utah",
    description: "Known for preserving over 2,000 natural sandstone arches, including the world-famous Delicate Arch.",
    established: 1971,
    visitors: 1585718,
    latitude: 38.7331,
    longitude: -109.5925,
    website: "https://www.nps.gov/arch/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Arches National Park Delicate Arch sunset",
  },
  {
    id: 12,
    name: "Grand Teton",
    type: "National Park",
    state: "Wyoming",
    description: "Features the majestic Teton Range, pristine lakes, and extraordinary wildlife.",
    established: 1929,
    visitors: 3405614,
    latitude: 43.7904,
    longitude: -110.6818,
    website: "https://www.nps.gov/grte/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Grand Teton National Park mountains reflection lake",
  },
  {
    id: 13,
    name: "Glacier",
    type: "National Park",
    state: "Montana",
    description: "Known for its pristine forests, alpine meadows, rugged mountains, and spectacular lakes.",
    established: 1910,
    visitors: 3049839,
    latitude: 48.7596,
    longitude: -113.787,
    website: "https://www.nps.gov/glac/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Glacier National Park Going-to-the-Sun Road",
  },
  {
    id: 14,
    name: "Bryce Canyon",
    type: "National Park",
    state: "Utah",
    description: "Famous for its unique geology of red rock spires and horseshoe-shaped amphitheaters.",
    established: 1928,
    visitors: 2679478,
    latitude: 37.593,
    longitude: -112.1871,
    website: "https://www.nps.gov/brca/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Bryce Canyon National Park hoodoos sunrise",
  },
  {
    id: 15,
    name: "Canyonlands",
    type: "National Park",
    state: "Utah",
    description:
      "Preserves a colorful landscape eroded into countless canyons, mesas, and buttes by the Colorado River and its tributaries.",
    established: 1964,
    visitors: 776218,
    latitude: 38.2136,
    longitude: -109.9025,
    website: "https://www.nps.gov/cany/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Canyonlands National Park Mesa Arch sunrise",
  },
  {
    id: 16,
    name: "Capitol Reef",
    type: "National Park",
    state: "Utah",
    description:
      "Features the Waterpocket Fold, a geologic monocline (a wrinkle on the earth) extending almost 100 miles.",
    established: 1971,
    visitors: 1227627,
    latitude: 38.367,
    longitude: -111.2615,
    website: "https://www.nps.gov/care/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Capitol Reef National Park Waterpocket Fold",
  },
  {
    id: 17,
    name: "Carlsbad Caverns",
    type: "National Park",
    state: "New Mexico",
    description:
      "Features more than 119 caves, formed when sulfuric acid dissolved limestone, creating some of the largest caves in North America.",
    established: 1930,
    visitors: 466773,
    latitude: 32.1478,
    longitude: -104.5567,
    website: "https://www.nps.gov/cave/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Carlsbad Caverns National Park underground formations",
  },
  {
    id: 18,
    name: "Channel Islands",
    type: "National Park",
    state: "California",
    description:
      "Encompasses five of the eight Channel Islands off the coast of California, known for their endemic plants and animals.",
    established: 1980,
    visitors: 366250,
    latitude: 34.0069,
    longitude: -119.7785,
    website: "https://www.nps.gov/chis/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Channel Islands National Park coastal view",
  },
  {
    id: 19,
    name: "Crater Lake",
    type: "National Park",
    state: "Oregon",
    description:
      "Famous for its deep blue water and 2,000 foot cliff walls, Crater Lake was formed by the collapse of Mount Mazama volcano.",
    established: 1902,
    visitors: 704512,
    latitude: 42.9446,
    longitude: -122.109,
    website: "https://www.nps.gov/crla/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Crater Lake National Park deep blue water",
  },
  {
    id: 20,
    name: "Death Valley",
    type: "National Park",
    state: "California, Nevada",
    description: "The hottest, driest, and lowest national park, featuring Badwater Basin at 282 feet below sea level.",
    established: 1994,
    visitors: 1678660,
    latitude: 36.5323,
    longitude: -116.9325,
    website: "https://www.nps.gov/deva/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Death Valley National Park Badwater Basin salt flats",
  },
  {
    id: 21,
    name: "Denali",
    type: "National Park",
    state: "Alaska",
    description: "Home to North America's highest peak, Denali (formerly Mount McKinley), standing at 20,310 feet.",
    established: 1917,
    visitors: 594660,
    latitude: 63.1148,
    longitude: -151.1926,
    website: "https://www.nps.gov/dena/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Denali National Park mountain peak wildlife",
  },
  {
    id: 22,
    name: "Dry Tortugas",
    type: "National Park",
    state: "Florida",
    description: "Known for its clear blue waters, coral reefs, and Fort Jefferson, a massive 19th-century fort.",
    established: 1992,
    visitors: 78488,
    latitude: 24.6285,
    longitude: -82.8732,
    website: "https://www.nps.gov/drto/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Dry Tortugas National Park Fort Jefferson aerial",
  },
  {
    id: 23,
    name: "Gates of the Arctic",
    type: "National Park",
    state: "Alaska",
    description:
      "The northernmost national park in the U.S., with no roads or trails, preserving the wild and undeveloped Arctic landscape.",
    established: 1980,
    visitors: 9591,
    latitude: 67.7805,
    longitude: -153.2917,
    website: "https://www.nps.gov/gaar/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Gates of the Arctic National Park wilderness mountains",
  },
  {
    id: 24,
    name: "Glacier Bay",
    type: "National Park",
    state: "Alaska",
    description: "Features tidewater glaciers, deep fjords, and a temperate rainforest ecosystem.",
    established: 1980,
    visitors: 672087,
    latitude: 58.6658,
    longitude: -136.9002,
    website: "https://www.nps.gov/glba/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Glacier Bay National Park calving glacier",
  },
  {
    id: 25,
    name: "Guadalupe Mountains",
    type: "National Park",
    state: "Texas",
    description:
      "Home to the highest peak in Texas, Guadalupe Peak, and the world's most extensive Permian fossil reef.",
    established: 1972,
    visitors: 219987,
    latitude: 31.9231,
    longitude: -104.8645,
    website: "https://www.nps.gov/gumo/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Guadalupe Mountains National Park El Capitan peak",
  },
  {
    id: 26,
    name: "Haleakalā",
    type: "National Park",
    state: "Hawaii",
    description:
      "Features the dormant Haleakalā Volcano and is known for its spectacular sunrises and unique volcanic landscape.",
    established: 1961,
    visitors: 1044084,
    latitude: 20.7204,
    longitude: -156.1552,
    website: "https://www.nps.gov/hale/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Haleakala National Park crater sunrise",
  },
  {
    id: 27,
    name: "Hawaii Volcanoes",
    type: "National Park",
    state: "Hawaii",
    description:
      "Home to two active volcanoes: Kīlauea, one of the world's most active, and Mauna Loa, the world's most massive shield volcano.",
    established: 1916,
    visitors: 1262747,
    latitude: 19.3833,
    longitude: -155.2,
    website: "https://www.nps.gov/havo/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Hawaii Volcanoes National Park Kilauea lava flow",
  },
  {
    id: 28,
    name: "Hot Springs",
    type: "National Park",
    state: "Arkansas",
    description: "Preserves 47 hot springs that flow from the western slope of Hot Springs Mountain.",
    established: 1921,
    visitors: 1506887,
    latitude: 34.5037,
    longitude: -93.0552,
    website: "https://www.nps.gov/hosp/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Hot Springs National Park bathhouse row",
  },
  {
    id: 29,
    name: "Isle Royale",
    type: "National Park",
    state: "Michigan",
    description: "An isolated island archipelago in Lake Superior, known for its wolf and moose populations.",
    established: 1940,
    visitors: 25798,
    latitude: 48.0,
    longitude: -88.8,
    website: "https://www.nps.gov/isro/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Isle Royale National Park moose lake",
  },
  {
    id: 30,
    name: "Joshua Tree",
    type: "National Park",
    state: "California",
    description: "Named for its twisted, bristled Joshua trees, this park straddles the Colorado and Mojave Deserts.",
    established: 1994,
    visitors: 3058294,
    latitude: 33.8734,
    longitude: -115.901,
    website: "https://www.nps.gov/jotr/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Joshua Tree National Park rock formations sunset",
  },
  {
    id: 31,
    name: "Katmai",
    type: "National Park",
    state: "Alaska",
    description:
      "Known for the Valley of Ten Thousand Smokes and for its brown bears, which can be observed catching salmon at Brooks Falls.",
    established: 1980,
    visitors: 84167,
    latitude: 58.6126,
    longitude: -155.0631,
    website: "https://www.nps.gov/katm/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Katmai National Park bear catching salmon",
  },
  {
    id: 32,
    name: "Kenai Fjords",
    type: "National Park",
    state: "Alaska",
    description:
      "Protects the Harding Icefield, one of the largest ice fields in the United States, and its outflowing glaciers.",
    established: 1980,
    visitors: 356601,
    latitude: 59.8083,
    longitude: -150.1066,
    website: "https://www.nps.gov/kefj/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Kenai Fjords National Park Exit Glacier",
  },
  {
    id: 33,
    name: "Kings Canyon",
    type: "National Park",
    state: "California",
    description: "Features the deepest canyon in the United States and giant sequoia trees.",
    established: 1940,
    visitors: 632110,
    latitude: 36.8879,
    longitude: -118.5551,
    website: "https://www.nps.gov/seki/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Kings Canyon National Park giant sequoia trees",
  },
  {
    id: 34,
    name: "Kobuk Valley",
    type: "National Park",
    state: "Alaska",
    description: "Contains the Great Kobuk Sand Dunes, the largest active sand dunes in the Arctic.",
    established: 1980,
    visitors: 15766,
    latitude: 67.35,
    longitude: -159.2833,
    website: "https://www.nps.gov/kova/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Kobuk Valley National Park sand dunes arctic",
  },
  {
    id: 35,
    name: "Lake Clark",
    type: "National Park",
    state: "Alaska",
    description: "Features active volcanoes, salmon-bearing rivers, glaciers, waterfalls, and diverse wildlife.",
    established: 1980,
    visitors: 17157,
    latitude: 60.97,
    longitude: -153.41,
    website: "https://www.nps.gov/lacl/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Lake Clark National Park bears fishing",
  },
  {
    id: 36,
    name: "Lassen Volcanic",
    type: "National Park",
    state: "California",
    description: "Features all four types of volcanoes: shield, composite, cinder cone, and plug dome.",
    established: 1916,
    visitors: 542274,
    latitude: 40.4977,
    longitude: -121.4207,
    website: "https://www.nps.gov/lavo/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Lassen Volcanic National Park Bumpass Hell",
  },
  {
    id: 37,
    name: "Mammoth Cave",
    type: "National Park",
    state: "Kentucky",
    description: "The world's longest known cave system, with more than 400 miles of surveyed passageways.",
    established: 1941,
    visitors: 522628,
    latitude: 37.1862,
    longitude: -86.1,
    website: "https://www.nps.gov/maca/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Mammoth Cave National Park underground formations",
  },
  {
    id: 38,
    name: "Mesa Verde",
    type: "National Park",
    state: "Colorado",
    description: "Protects some of the best preserved Ancestral Puebloan archaeological sites in the United States.",
    established: 1906,
    visitors: 563420,
    latitude: 37.2309,
    longitude: -108.4618,
    website: "https://www.nps.gov/meve/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Mesa Verde National Park Cliff Palace",
  },
  {
    id: 39,
    name: "Mount Rainier",
    type: "National Park",
    state: "Washington",
    description: "An active stratovolcano and the most glaciated peak in the contiguous U.S.",
    established: 1899,
    visitors: 1518491,
    latitude: 46.88,
    longitude: -121.7269,
    website: "https://www.nps.gov/mora/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Mount Rainier National Park reflection lake wildflowers",
  },
  {
    id: 40,
    name: "North Cascades",
    type: "National Park",
    state: "Washington",
    description: "Features rugged mountain peaks, deep valleys, cascading waterfalls, and over 300 glaciers.",
    established: 1968,
    visitors: 38208,
    latitude: 48.7718,
    longitude: -121.2985,
    website: "https://www.nps.gov/noca/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=North Cascades National Park jagged peaks",
  },
  {
    id: 41,
    name: "Petrified Forest",
    type: "National Park",
    state: "Arizona",
    description:
      "Known for its large deposits of petrified wood, as well as its colorful badlands called the Painted Desert.",
    established: 1962,
    visitors: 644922,
    latitude: 35.0037,
    longitude: -109.7889,
    website: "https://www.nps.gov/pefo/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Petrified Forest National Park colorful logs",
  },
  {
    id: 42,
    name: "Redwood",
    type: "National Park",
    state: "California",
    description: "Protects vast forests of the world's tallest trees, the coast redwood.",
    established: 1968,
    visitors: 504722,
    latitude: 41.2132,
    longitude: -124.0046,
    website: "https://www.nps.gov/redw/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Redwood National Park tall trees sunlight",
  },
  {
    id: 43,
    name: "Saguaro",
    type: "National Park",
    state: "Arizona",
    description: "Named for the large saguaro cactus, native to the Sonoran Desert.",
    established: 1994,
    visitors: 957405,
    latitude: 32.2967,
    longitude: -111.1666,
    website: "https://www.nps.gov/sagu/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Saguaro National Park cactus sunset",
  },
  {
    id: 44,
    name: "Sequoia",
    type: "National Park",
    state: "California",
    description: "Home to giant sequoias, including the General Sherman Tree, the largest tree on Earth by volume.",
    established: 1890,
    visitors: 1246053,
    latitude: 36.4864,
    longitude: -118.5658,
    website: "https://www.nps.gov/seki/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Sequoia National Park General Sherman Tree",
  },
  {
    id: 45,
    name: "Theodore Roosevelt",
    type: "National Park",
    state: "North Dakota",
    description:
      "Memorializes the 26th president for his contributions to conservation, featuring badlands, petrified wood, and wildlife.",
    established: 1978,
    visitors: 749389,
    latitude: 46.979,
    longitude: -103.5387,
    website: "https://www.nps.gov/thro/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Theodore Roosevelt National Park bison badlands",
  },
  {
    id: 46,
    name: "Virgin Islands",
    type: "National Park",
    state: "U.S. Virgin Islands",
    description: "Preserves beautiful beaches, coral reefs, historic ruins, and tropical forests.",
    established: 1956,
    visitors: 323999,
    latitude: 18.3383,
    longitude: -64.7281,
    website: "https://www.nps.gov/viis/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Virgin Islands National Park tropical beach",
  },
  {
    id: 47,
    name: "Voyageurs",
    type: "National Park",
    state: "Minnesota",
    description: "A maze of interconnected water highways, with over 40% of the park being water.",
    established: 1975,
    visitors: 239656,
    latitude: 48.4725,
    longitude: -92.8492,
    website: "https://www.nps.gov/voya/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Voyageurs National Park lakes sunset",
  },
  {
    id: 48,
    name: "Wind Cave",
    type: "National Park",
    state: "South Dakota",
    description:
      "Known for its boxwork formations, a rare cave feature composed of thin calcite fins resembling honeycombs.",
    established: 1903,
    visitors: 709001,
    latitude: 43.5724,
    longitude: -103.4391,
    website: "https://www.nps.gov/wica/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Wind Cave National Park boxwork formations",
  },
  {
    id: 49,
    name: "Wrangell-St. Elias",
    type: "National Park",
    state: "Alaska",
    description: "America's largest national park, containing numerous glaciers and peaks above 16,000 feet.",
    established: 1980,
    visitors: 79450,
    latitude: 61.7104,
    longitude: -142.9857,
    website: "https://www.nps.gov/wrst/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Wrangell-St. Elias National Park mountains glaciers",
  },
  {
    id: 50,
    name: "Badlands",
    type: "National Park",
    state: "South Dakota",
    description:
      "Contains one of the world's richest fossil beds, displaying ancient mammals such as the rhino, horse, and saber-toothed cat.",
    established: 1978,
    visitors: 1224226,
    latitude: 43.8554,
    longitude: -102.3397,
    website: "https://www.nps.gov/badl/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Badlands National Park colorful rock formations",
  },
  {
    id: 51,
    name: "Big Bend",
    type: "National Park",
    state: "Texas",
    description:
      "Named for the large bend in the Rio Grande along the U.S.–Mexico border, featuring river canyons and desert landscapes.",
    established: 1944,
    visitors: 581220,
    latitude: 29.2498,
    longitude: -103.2502,
    website: "https://www.nps.gov/bibe/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Big Bend National Park Rio Grande river canyon",
  },
  {
    id: 52,
    name: "Black Canyon of the Gunnison",
    type: "National Park",
    state: "Colorado",
    description: "Features some of the steepest cliffs, oldest rock, and craggiest spires in North America.",
    established: 1999,
    visitors: 308962,
    latitude: 38.5754,
    longitude: -107.7416,
    website: "https://www.nps.gov/blca/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Black Canyon of the Gunnison steep walls",
  },
  {
    id: 53,
    name: "Congaree",
    type: "National Park",
    state: "South Carolina",
    description: "Preserves the largest tract of old growth bottomland hardwood forest in the United States.",
    established: 2003,
    visitors: 215181,
    latitude: 33.7948,
    longitude: -80.7821,
    website: "https://www.nps.gov/cong/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Congaree National Park boardwalk swamp",
  },
  {
    id: 54,
    name: "Cuyahoga Valley",
    type: "National Park",
    state: "Ohio",
    description: "Preserves and reclaims the rural landscape along the Cuyahoga River between Akron and Cleveland.",
    established: 2000,
    visitors: 2913312,
    latitude: 41.2808,
    longitude: -81.5678,
    website: "https://www.nps.gov/cuva/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Cuyahoga Valley National Park Brandywine Falls",
  },
  {
    id: 55,
    name: "Gateway Arch",
    type: "National Park",
    state: "Missouri",
    description:
      "Commemorates the westward expansion of the United States, featuring the iconic 630-foot Gateway Arch.",
    established: 2018,
    visitors: 2055309,
    latitude: 38.627,
    longitude: -90.1847,
    website: "https://www.nps.gov/jeff/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Gateway Arch National Park St Louis",
  },
  {
    id: 56,
    name: "Great Basin",
    type: "National Park",
    state: "Nevada",
    description: "Features ancient bristlecone pines, limestone caves, and the only glacier in Nevada.",
    established: 1986,
    visitors: 144875,
    latitude: 38.93,
    longitude: -114.2634,
    website: "https://www.nps.gov/grba/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Great Basin National Park bristlecone pine",
  },
  {
    id: 57,
    name: "Great Sand Dunes",
    type: "National Park",
    state: "Colorado",
    description: "Contains the tallest sand dunes in North America, rising to a maximum height of 750 feet.",
    established: 2004,
    visitors: 602613,
    latitude: 37.7917,
    longitude: -105.5944,
    website: "https://www.nps.gov/grsa/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Great Sand Dunes National Park tallest dunes",
  },
  {
    id: 58,
    name: "Indiana Dunes",
    type: "National Park",
    state: "Indiana",
    description: "Features 15 miles of Lake Michigan shoreline, with beaches, dunes, wetlands, and forests.",
    established: 2019,
    visitors: 2293106,
    latitude: 41.6533,
    longitude: -87.0524,
    website: "https://www.nps.gov/indu/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Indiana Dunes National Park Lake Michigan",
  },
  {
    id: 59,
    name: "New River Gorge",
    type: "National Park",
    state: "West Virginia",
    description: "Preserves and protects the New River Gorge, featuring one of the oldest rivers on the continent.",
    established: 2020,
    visitors: 1682720,
    latitude: 37.8776,
    longitude: -81.0189,
    website: "https://www.nps.gov/neri/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=New River Gorge Bridge West Virginia",
  },
  {
    id: 60,
    name: "Pinnacles",
    type: "National Park",
    state: "California",
    description:
      "Named for the eroded leftovers of an extinct volcano, featuring massive monoliths, spires, and talus caves.",
    established: 2013,
    visitors: 275023,
    latitude: 36.4906,
    longitude: -121.1825,
    website: "https://www.nps.gov/pinn/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Pinnacles National Park rock formations",
  },
  {
    id: 61,
    name: "White Sands",
    type: "National Park",
    state: "New Mexico",
    description: "Features wave-like dunes of gypsum sand that engulf 275 square miles of desert.",
    established: 2019,
    visitors: 782469,
    latitude: 32.7872,
    longitude: -106.3257,
    website: "https://www.nps.gov/whsa/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=White Sands National Park gypsum dunes",
  },
  {
    id: 62,
    name: "American Samoa",
    type: "National Park",
    state: "American Samoa",
    description:
      "The only U.S. national park south of the equator, preserving coral reefs, rainforests, and Samoan culture.",
    established: 1988,
    visitors: 8495,
    latitude: -14.2583,
    longitude: -170.6833,
    website: "https://www.nps.gov/npsa/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=American Samoa National Park tropical coastline",
  },
  {
    id: 63,
    name: "Biscayne",
    type: "National Park",
    state: "Florida",
    description: "Protects a rare combination of aquamarine waters, emerald islands, and coral reefs.",
    established: 1980,
    visitors: 708522,
    latitude: 25.4824,
    longitude: -80.2083,
    website: "https://www.nps.gov/bisc/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Biscayne National Park coral reef underwater",
  },
  {
    id: 64,
    name: "Grand Staircase-Escalante",
    type: "National Monument",
    state: "Utah",
    description: "A vast and rugged landscape featuring colorful cliffs, plateaus, mesas, buttes, and canyons.",
    established: 1996,
    visitors: 1001161,
    latitude: 37.4,
    longitude: -111.6833,
    website:
      "https://www.blm.gov/programs/national-conservation-lands/utah/grand-staircase-escalante-national-monument",
    image: "/placeholder.svg?height=300&width=500&query=Grand Staircase-Escalante colorful rock formations",
  },
  {
    id: 65,
    name: "Bears Ears",
    type: "National Monument",
    state: "Utah",
    description:
      "Named for a pair of buttes that resemble bear ears, containing ancient cliff dwellings and sacred tribal lands.",
    established: 2016,
    visitors: 418684,
    latitude: 37.6217,
    longitude: -109.8661,
    website: "https://www.blm.gov/programs/national-conservation-lands/utah/bears-ears-national-monument",
    image: "/placeholder.svg?height=300&width=500&query=Bears Ears National Monument buttes",
  },
  {
    id: 66,
    name: "Statue of Liberty",
    type: "National Monument",
    state: "New York",
    description: "A colossal neoclassical sculpture on Liberty Island, a gift from France to the United States.",
    established: 1924,
    visitors: 4240461,
    latitude: 40.6892,
    longitude: -74.0445,
    website: "https://www.nps.gov/stli/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Statue of Liberty National Monument",
  },
  {
    id: 67,
    name: "Mount St. Helens",
    type: "National Volcanic Monument",
    state: "Washington",
    description: "Site of the deadliest and most economically destructive volcanic event in U.S. history.",
    established: 1982,
    visitors: 651000,
    latitude: 46.1914,
    longitude: -122.1956,
    website: "https://www.fs.usda.gov/recarea/giffordpinchot/recarea/?recid=31562",
    image: "/placeholder.svg?height=300&width=500&query=Mount St Helens volcano crater",
  },
  {
    id: 68,
    name: "Devils Tower",
    type: "National Monument",
    state: "Wyoming",
    description: "A monolithic igneous intrusion or volcanic neck with distinctive columnar jointing.",
    established: 1906,
    visitors: 448405,
    latitude: 44.5902,
    longitude: -104.7146,
    website: "https://www.nps.gov/deto/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Devils Tower National Monument",
  },
  {
    id: 69,
    name: "Muir Woods",
    type: "National Monument",
    state: "California",
    description: "An old-growth coastal redwood forest, with trees over 250 feet tall and 800 years old.",
    established: 1908,
    visitors: 957932,
    latitude: 37.8912,
    longitude: -122.5719,
    website: "https://www.nps.gov/muwo/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Muir Woods National Monument redwoods",
  },
  {
    id: 70,
    name: "Craters of the Moon",
    type: "National Monument",
    state: "Idaho",
    description: "A vast ocean of lava flows with scattered islands of cinder cones and sagebrush.",
    established: 1924,
    visitors: 264104,
    latitude: 43.4166,
    longitude: -113.5166,
    website: "https://www.nps.gov/crmo/index.htm",
    image: "/placeholder.svg?height=300&width=500&query=Craters of the Moon lava field",
  },
]
